"""Job suite: prompt the model to produce JSON matching a schema, validate it."""

from __future__ import annotations

import json
from typing import Callable

import jsonschema

from ..data.generated_json_schema_problems import generate_problems
from ..data.json_schema_problems import PROBLEMS
from ..engine import RunContext
from ..json_extract import extract_json
from ..results import ProblemResult

SYSTEM_PROMPT = (
    "You are a JSON generation engine. Respond with ONLY a single valid JSON "
    "value that satisfies the user's request. Do not include markdown code "
    "fences, explanations, or any text other than the JSON itself."
)


def _run_one(problem: dict, ctx: RunContext, call_kwargs: dict) -> ProblemResult:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                f"{problem['task']}\n\n"
                f"The JSON must validate against this JSON Schema:\n"
                f"{json.dumps(problem['schema'], indent=2)}"
            ),
        },
    ]

    chat = ctx.call(messages, **call_kwargs)
    prompt_val = messages[1]["content"] if len(messages) > 1 else str(messages)

    if not chat.success:
        return ProblemResult(
            problem_id=problem["id"],
            passed=False,
            error=f"call failed: {chat.error}",
            latency_seconds=chat.latency_seconds,
            ttft_seconds=chat.ttft_seconds,
            prompt=prompt_val,
        )

    if chat.truncated:
        return ProblemResult(
            problem_id=problem["id"],
            passed=False,
            error="response truncated at max_tokens before completion (finish_reason=length)",
            latency_seconds=chat.latency_seconds,
            ttft_seconds=chat.ttft_seconds,
            prompt_tokens=chat.prompt_tokens,
            completion_tokens=chat.completion_tokens,
            prompt=prompt_val,
            response_content=chat.content,
            reasoning_content=chat.reasoning_content,
            truncated=True,
        )

    value, extract_error = extract_json(chat.content)
    if extract_error:
        return ProblemResult(
            problem_id=problem["id"],
            passed=False,
            error=extract_error,
            latency_seconds=chat.latency_seconds,
            ttft_seconds=chat.ttft_seconds,
            prompt_tokens=chat.prompt_tokens,
            completion_tokens=chat.completion_tokens,
            prompt=prompt_val,
            response_content=chat.content,
            reasoning_content=chat.reasoning_content,
        )

    try:
        jsonschema.validate(instance=value, schema=problem["schema"])
        return ProblemResult(
            problem_id=problem["id"],
            passed=True,
            latency_seconds=chat.latency_seconds,
            ttft_seconds=chat.ttft_seconds,
            prompt_tokens=chat.prompt_tokens,
            completion_tokens=chat.completion_tokens,
            prompt=prompt_val,
            response_content=chat.content,
            reasoning_content=chat.reasoning_content,
        )
    except jsonschema.ValidationError as e:
        return ProblemResult(
            problem_id=problem["id"],
            passed=False,
            error=f"schema validation failed at {list(e.absolute_path)}: {e.message}",
            latency_seconds=chat.latency_seconds,
            ttft_seconds=chat.ttft_seconds,
            prompt_tokens=chat.prompt_tokens,
            completion_tokens=chat.completion_tokens,
            prompt=prompt_val,
            response_content=chat.content,
            reasoning_content=chat.reasoning_content,
        )


def run(
    ctx: RunContext,
    problems: list[dict] | None = None,
    max_tokens: int | None = None,
    call_timeout_seconds: float | None = None,
    on_progress: Callable[[int, int, str, bool], None] | None = None,
    generated: bool = True,
    num_problems: int = 20,
    seed: int = 42,
) -> list[ProblemResult]:
    # Generated by default: the old fixed set was only 5 problems, giving a
    # confidence interval too wide to conclude anything. Set generated: false
    # to fall back to it.
    if problems is None:
        problems = generate_problems(num_problems, seed) if generated else PROBLEMS
    results: list[ProblemResult] = []
    call_kwargs = {}
    if max_tokens is not None:
        call_kwargs["max_tokens"] = max_tokens
    if call_timeout_seconds is not None:
        call_kwargs["timeout_seconds"] = call_timeout_seconds

    for idx, problem in enumerate(problems):
        result = _run_one(problem, ctx, call_kwargs)
        results.append(result)
        if on_progress:
            on_progress(idx + 1, len(problems), result.problem_id, result.passed, result=result)

    return results
